name: Hello wordl flow

on:
  push:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print the name of "hellow world"
        run: echo "Hello World!"
      - name: print the current date
        run: date
      - name: print the current working directory
        run: pwd
      - name: list files
        run: ls -la