name: Dispatch workflow

on:
  workflow_dispatch:
    inputs:
      john:
        type: boolean
        default: false

      jane:
        type: boolean
        default: false

      jack:
        type: boolean
        default: false

jobs:
  say-hello:
    runs-on: ubuntu-latest

    env:
      JOHN: ${{ inputs.john }}
      JANE: ${{ inputs.jane }}
      JACK: ${{ inputs.jack }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load .env file
        run: |
          cat sfa/env/.env | grep -v '^#' | grep -v '^$' >> $GITHUB_ENV

      - name: Print selected names
        run: |
          NAMES=()
          for pair in "JOHN:NAME1" "JANE:NAME2" "JACK:NAME3"; do
            checkbox="${pair%%:*}"
            name_var="${pair##*:}"
            [[ "${!checkbox}" == "true" ]] && NAMES+=("${!name_var}")
          done
          echo "Selected names: ${NAMES[*]}"


      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dep...
        run: pip install requests

      - name: Run hello.py script
        run: |
          NAMES=()
          for pair in "JOHN:NAME1" "JANE:NAME2" "JACK:NAME3"; do
            checkbox="${pair%%:*}"
            name_var="${pair##*:}"
            [[ "${!checkbox}" == "true" ]] && NAMES+=("${!name_var}")
          done
          python hello.py "$(IFS=,; echo "${NAMES[*]}")"
