name: Test retry-cmd

on:
  workflow_dispatch:

jobs:
  retry-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install retry-cmd
        run: |
          cargo install retry-cmd

      - name: Verify installation
        run: |
          retry --max 3 --interval 60 -- bash -eux -c '
            retry --version
          '

      - name: Test 1 - Success on first attempt
        shell: bash
        run: |
          retry --max 3 --interval 5 -- bash -eux -c '
            lsd
            curl  --connect-timeout 2 http://192.0.2.1/config.json
          '
